### ISSUE TITLE
版本应该是符合的，但是还是报错了

### ISSUE THREAD

**Issue by ekko-zhao** [BreakOnCrash/wxapkg#1]
<img width="937" alt="image" src="https://github.com/ac0d3r/wxapkg/assets/26781518/3be688e0-767d-4175-99a9-6a6121587399">
可以帮忙看看什么问题吗

**Comment by ac0d3r** [comment]
3.8.0 小版本没测试过，检查你当前微信版本下存放 `wxapplet` 文件是否是`~/Library/Containers/com.tencent.xinWeChat/Data/.wxapplet/packages/`路径？

**Comment by SiYuan-Rao** [comment]
我的也是3.8.0版本的，可以正常使用。
